### ISSUE TITLE
Errors not reports / currently not working?

### ISSUE THREAD

**Issue by apowers313** [kevnull/pivotal-tracker-alfred-workflow#1]
Love the idea of this script, thanks for putting it together.

After setting up the values in the script, I tried to add a new story and got a notification "Added Story", but the story didn't show up in PT.

I did some debugging and found that running the curl command from bash (with the appropriate values replaced) returned "Access Denied". 

So I guess I have two issues -- 
1. the script should catch the return values of `shell_exec` and `SimpleXMLElement` and report an error if one occurs; 
2. has PT changed their URLs / APIs since the last time this was updated?

FWIW, I'm running Alfred3, but I don't think that should make a difference here.

Thanks!

**Comment by apowers313** [comment]
One more tip, the [PT v5 API](https://www.pivotaltracker.com/help/api/rest/v5#Stories) appears to have switch to JSON for their encoding.

This seems to work:

``` bash
curl  -H "X-TrackerToken: $token" -H "Content-Type: application/json" -X POST --data "{\"name\":\"test\"}" https://www.pivotaltracker.com/services/v5/projects/$project/stories
```

**Comment by apowers313** [comment]
Sorry for the spam -- I didn't expect to actually fix this so quickly. Here's the working command for the script:

``` php
$cmd = "curl -H \"X-TrackerToken: ".$token."\" "
    . "-X POST -H \"Content-type: application/json\" "
    . "--data \"{\\\"name\\\":\\\"".$name."\\\"}\" "
    . "https://www.pivotaltracker.com/services/v5/projects/".$project."/stories";
```

This also requires commenting out the XML parsing:

``` php
//$story = new SimpleXMLElement($xml);
```

...which breaks the notification. I'm not sure how to parse JSON in PHP and I'm not likely to fix that part of it. :)

**Comment by kevnull** [comment]
Thanks for the notes and fix. I've updated the script. Have you tested this on Alfred v3? I haven't but would like to know to update that it's been tested for that as well.

**Comment by apowers313** [comment]
Yep, I'm running `Alfred 3.2, Build 759, Tuesday 8th November 2016`.
